version: '3.9'

services:
  app:
    build: .
    container_name: count_app 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - dj_redis_data:/data



volumes:
  dj_redis_data:
